apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: btc-price-checker
  name: btc-price-checker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: btc-price-checker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: btc-price-checker
    spec:
      containers:
        - image: btc-price-checker:latest
          imagePullPolicy: IfNotPresent
          name: btc-price-checker
          readinessProbe:
            httpGet:
              port: 8090
              path: /actuator/health
          livenessProbe:
            httpGet:
              port: 8090
              path: /actuator/health
          envFrom:
            - configMapRef:
                name: btc-price-checker
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: btc-price-checker
  name: btc-price-checker
  namespace: default
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: btc-price-checker
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
data:
  SPRING_PROFILES_ACTIVE: k8s
  DB_URL: jdbc:mariadb://localhost:3306/btc
  REDIS_HOST: localhost
kind: ConfigMap
metadata:
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: { }
          f:CURRENCY_EXCHANGE_URI: { }
      manager: kubectl.exe
      operation: Update
      time: 2021-10-27T17:22:56Z
  name: btc-price-checker
  namespace: default