version: '3.8'

services:
  btc-maria-db:
    image: mariadb:10.7
    container_name: btc-maria-db
    volumes:
      - '/var/lib/docker/volumes/btc/mariadb_btc:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: qaz123
      MYSQL_DATABASE: btc
      MYSQL_USER: btc
      MYSQL_PASSWORD: qaz123
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent", "-u", "root", "-pqaz123" ]
    ports:
      - "3306:3306"
    networks:
      - btc-network

  btc-redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - btc-network


networks:
  btc-network:
