version: '3.8'

services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:latest
    container_name: redis-node-0
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    ports:
      - "6380:6379"
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    networks:
      - redis-network

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:latest
    container_name: redis-node-1
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    ports:
      - "6381:6379"
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    networks:
      - redis-network

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:latest
    container_name: redis-node-2
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    ports:
      - "6382:6379"
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    networks:
      - redis-network


  redis-node-3:
    image: docker.io/bitnami/redis-cluster:latest
    container_name: redis-node-3
    volumes:
      - redis-cluster_data-3:/bitnami/redis/data
    ports:
      - "6383:6379"
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    networks:
      - redis-network

  redis-node-4:
    image: docker.io/bitnami/redis-cluster:latest
    container_name: redis-node-4
    volumes:
      - redis-cluster_data-4:/bitnami/redis/data
    ports:
      - "6384:6379"
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    networks:
      - redis-network


  redis-node-5:
    image: docker.io/bitnami/redis-cluster:latest
    container_name: redis-node-5
    volumes:
      - redis-cluster_data-5:/bitnami/redis/data
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    ports:
      - "6385:6379"
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDISCLI_AUTH=bitnami'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4'
      - 'REDIS_CLUSTER_CREATOR=yes'
    networks:
      - redis-network


networks:
  redis-network:

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local